language: node_js
node_js:
- '4.4.7'
branches:
  only:
  - master

before_install:
- git submodule update
- git config --global user.name "Build Bot"
- git config --global user.email jim@lotlab.org

install:
- npm install minori -g

script:
- minori d
- minori c
