# MinoriWiki Configuration
# ========================
# https://github.com/phoenixlzx/MinoriWiki

# Wiki
wiki:
  title: Lotlab Wiki
  tagline: Yet another static wiki
  description: Lotlab Wiki Site
  author: Jim Jiang
  email: jim(at)lotlab.org
  language: zh-CN
  theme: minori-mui
  favicon: true    # put your favicon.ico into MinoriWiki site configuration root directory
  log: true    # enable commit logs (will be displayed in public)
  logmax: 20    # maximum log amount to be displayed (to avoid very large webpage), default to 20.

# Base
base:
  uri: https://wiki.lotlab.org    # domain and protocol of your site, not containing any path and the final slash '/'
  path: /    # change this if you want your site to be in a sub-directory

# Directory
dir:
  source: notes    # notes source code
  static: static    # static files will be copied to <site root path>/static, to help you link any static file in articles
  site: wiki    # generated site files which are ready to be deployed
  raw: raw    # raw (source) note file in website directory
  page: page    # pages will write under this directory, e.g., /page/some-title, leave plank will write all pages under root

# Custom
custom:
  time: YYYY-MM-DD HH:mm:ss
  category: 未分类    # default category when creating new page
  markdown:
    html: true    # Enable HTML tags in source
    xhtmlOut: true    # Use '/' to close single tags (<br />)
    breaks: false    # Convert '\n' in paragraphs into <br> NOTE: some editors may trim tailing spaces so you may need this.
    langPrefix: 'language-'    # CSS language prefix for fenced blocks
    linkify: false    # Autoconvert URL-like text to links
    typographer: false    # Enable some language-neutral replacement + quotes beautification
    sup_sub: true    # superscripts and subscripts
    abbr: true    # abbreviations
    footnote: true    # footnote
    ins: false    # EXPERIMENTAL ++inseted text++
    mark: false    # EXPERIMENTAL ==marked text==
  mathjax: false    # enable MathJax TeX support, you need markdown.html set to true (allow html) to work
  autospacing: true    # use `pangunode` library to add space between CJK and Western characters automatically
  editor: Typora    # auto open your note after command
  lastupdate: "%n%%n%<div class='last-update'>此页面最后更新于: %mtime%</div>%n%"

theme:
  valine:
    appkey: PdPA1xgzmFdUQqugmfzYamF9
    appid: LxTBCCGY8s9s0U2QVIaudxk1-MdYXbMMI
    placeholder: 写下你的评论吧
    visitor: true
  greeting: 欢迎来到 Lotlab Wiki
  index_content: <h2>变更记录</h2><ul><li>2017-01-18 完全静态化，迁移至 Github Pages.</li><li>2015-11-07 替换庞大的 MediaWiki 为 DokuWiki </li></ul>
  side_links: 
    - others:
      name: "其他链接"
      links: 
        - github: 
          name: Github
          link: https://github.com/Lotlab/wiki
          external: true
        - term:
          name: 网站协议
          link: /page/terms
        - contribute:
          name: 贡献内容
          link: /page/contribute
        - changelog:
          name: 更新日志
          link: /changelog

# Deployment
deploy:
  repo: git@github.com:Lotlab/wiki.git
  branch: gh-pages
  cname: wiki.lotlab.org
  s3:
    enabled: false
    bucket: your-bucket-name
    region: us-west-1
    accessKeyId: yourapikey
    accessKeySecret: yourapisecret
  pushcommand:
    enabled: false
    command: /usr/bin/firebase deploy

